server:
  port: 8088

spring:
  application:
    name: spring-fuzzer

management:
  endpoints:
    web:
      exposure:
        include: health,info

afl:
  target-base-url: http://127.0.0.1:8000
  default-iterations: 50
  mutation-min: 1
  mutation-max: 3
